version: '3.8'

services:
  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=microservice
      - POSTGRES_USER=microservice
      - POSTGRES_PASSWORD=microservice
    networks:
      - microservice

  gateway:
    image: hoangthienclub/api-gateway
    environment:
      - PORT=3000
      - USER_SERVICE_URL=user
      - USER_SERVICE_PORT=3002
      - AUTH_SERVICE_URL=auth
      - AUTH_SERVICE_PORT=3001
    depends_on:
      - auth
      - user
    ports:
      - 3000:3000
    networks:
      - microservice

  auth:
    image: hoangthienclub/auth-service
    networks:
      - microservice
    environment:
      - PORT=3001

  user:
    image: hoangthienclub/user-service
    networks:
      - microservice
    environment:
      - PORT=3002


networks:
  microservice: